name: Node.js CI

on:
  release:
    types: [published]

jobs:
  linux-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run dist
      - name: 'Add assets to release'
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.deb
            dist/*.snap
            dist/*.tar.xz
      
  windows-dist:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run dist
      - name: 'Add assets to release'
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.exe
